### ISSUE TITLE
How to create a deb package from the source code?

### ISSUE THREAD

**Issue by mythravarun** [kravietz/pam_tacplus#133]
I may sound noob, but I am looking for some help with deb package creation from the source code. 

I tried below things:

1. mk-build-deps --install debian/control; debuild -uc -us -i -b
But facing below error:

> make[1]: *** [Makefile:1402: test] Error 1
> make[1]: Leaving directory '/root/pam_tacplus'
> dh_auto_test: make -j1 test VERBOSE=1 returned exit code 2
> make: *** [debian/rules:13: build] Error 2
> dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
> debuild: fatal error at line 1182:
> dpkg-buildpackage -us -uc -ui -i -b failed

2. make deb is not defined - I am seeing below error
> make: *** No rule to make target 'deb'.  Stop.

3. dpkg-buildpackage -B command is also not working. Giving below error

> make[1]: *** [Makefile:1402: test] Error 1
> make[1]: Leaving directory '/root/pam_tacplus'
> dh_auto_test: make -j1 test VERBOSE=1 returned exit code 2
> make: *** [debian/rules:13: build-arch] Error 2
> dpkg-buildpackage: error: debian/rules build-arch subprocess returned exit status 2

Is there any prerequisite steps before executing mentioned commands? Or are there any make options to build deb package?

**Comment by kravietz** [comment]
@mythravarun The `deb` building subsystem hasn't been touched for a while, and interfaces might have changed in the meantime. Can you try to debug the problem on your side for now? I'd be happy to accept a pull request but I can't dig into it right now.
