### ISSUE TITLE
error during tacc installation

### ISSUE THREAD

**Issue by CharlesParent** [kravietz/pam_tacplus#142]
Hello,

I tried to build a debian package from source using `debuild -uc -us -b` and had an issue regarding tacc installation:
`cp debian/tacplus debian/libpam-tacplus/usr/share/pam-configs/
dh_install
dh_install: Cannot find (any matches for) "usr/sbin" (tried in "." and "debian/tmp")
dh_install: libtac2-bin missing files: usr/sbin
dh_install: missing files, aborting
debian/rules:23: recipe for target 'override_dh_install' failed
`

It appears tacc executable is installed in debian/tmp/usr/bin and not debian/tmp/usr/sbin:
`libtool: install: /usr/bin/install -c .libs/tacc /libpam-tacplus/debian/tmp/usr/bin/tacc
`
Do you think there is something wrong with where tacc is installed or should the libtac2-bin.install file should be updated to /usr/bin instead ?

**Comment by kravietz** [comment]
`tacc` should definitely go to `/usr/bin` as it's a client tool, not a daemon
