### ISSUE TITLE
Submission of feature enhancement 

### ISSUE THREAD

**Issue by kinjal491** [kravietz/pam_tacplus#158]
can you share procedure to submit the feature enhancement/customization changes ?
- Timeout support for each Remote server 
- Connect to next server in case of multiple server configured 
- Added error message in case server is not configured, secrete key is not configured and secrete key error and passing staus up to to the Application
- sent out packet even if Bind to source address call fails

**Comment by kravietz** [comment]
@kinjal491 If you could submit a pull request, I'll be able to review and merge it really quick. Otherwise I have very limited capability for writing new code on the project now.

**Comment by akhileshsingh-saithwar** [comment]
> @kinjal491 If you could submit a pull request, I'll be able to review and merge it really quick. Otherwise I have very limited capability for writing new code on the project now.

Hi @kravietz : For this I created a branch src-addr-fix and merged changes and committed the changes. When I am triying to push the changes I am getting below error.

"
git push --set-upstream origin src-addr-fix
remote: Permission to kravietz/pam_tacplus.git denied to akhileshsingh-saithwar.
fatal: unable to access 'https://github.com/kravietz/pam_tacplus/': The requested URL returned error: 403
"
Do I need to have some access from you to push changes? @kinjal491 and me are colleagues.

**Comment by kravietz** [comment]
@akhileshsingh-saithwar You need to first fork of this repo, then make changes to your forked repo, and then create merge request. Please follow this guide https://guides.github.com/activities/forking/
