### ISSUE TITLE
Unable to access customized API added to pam_tacplus library

### ISSUE THREAD

**Issue by srikanthrsr** [kravietz/pam_tacplus#160]
I have added an Customized API in suport.c (definition) , support.h(declaration) , then i compiled library . 
Then tried to access it from my application (including support.h header file ) , 
and in makefile linked the library with option

LIBS = -ltac -lpam , then while compiling my application i got undefined reference error , 

even with the option LIBS = -ltac -lpam -L/usr/lib/pam_tacplus.so also i got the same undefined reference error

Can you please help me out, to solve this issue?

**Comment by kravietz** [comment]
@srikanthrsr Can you paste the error here?

**Comment by srikanthrsr** [comment]
> @srikanthrsr Can you paste the error here?

undefined reference to `getServerStats(char*)'

getServerStats is my customized API in support.c

**Comment by srikanthrsr** [comment]
undefined reference to `getServerStats(char*)'

**Comment by kravietz** [comment]
@srikanthrsr Have you installed `libtac` after compiling it with the custom code? I guess by default compiler will pick up the system-wide `libtac` on `-ltac` option, to point it to your local modified copy you need `-L dir`

**Comment by srikanthrsr** [comment]
Yes after compiling with custom code , i installed the libtac  and pam_tacplus.so in /usr/lib/ directory

Yes i even tried -L dir option as well but i got same error

**Comment by srikanthrsr** [comment]
I added custom API in tacacs/support.c , it will be compiled to pam_tacplus.so library , not to libtac.so

**Comment by kravietz** [comment]
@srikanthrsr This looks like incompatible libraries being installed at the same time in the system, not really bug in the `pam_tacplus`.
