### ISSUE TITLE
debian 11 package for libpam-tacplus

### ISSUE THREAD

**Issue by nvitaly** [kravietz/pam_tacplus#180]
Hello, I've been using libpam-tacplus with debian for ages, but it currently not availb with deb11
I know you do not support debian but Jeroen listed debian module maintainer, so I will ask:

do you have plan to compiling libpam-tacplus package for debian bullseye ? do you have appr ETA?

I tried to compile it myself (github head) and stuck on step "$ autoreconf -f -v -i" with error:

....
....
automake: warnings are treated as errors
Makefile.am:95: warning: clang -print-file-name=libclang_rt.asan-x86_64.so: non-POSIX variable name
Makefile.am:95: (probably a GNU make extension)
Makefile.am: installing 'config/depcomp'
autoreconf: automake failed with exit status: 1

sorry for packing two problem in one question

**Comment by mmehra** [comment]
+1

**Comment by sever-sever** [comment]
+1 @kravietz Are you planning to integrate it into Debian 11?

**Comment by kravietz** [comment]
@sever-sever I'd love to but I have little idea how to :(  With some help I'd be absolutely ready to maintain the integration in long term.

Also слава Україні! 🇺🇦

**Comment by kravietz** [comment]
BTW technically it's not hard to implement because in addition to the GitHub Actions this repo has a full build pipeline set up on SourceHut, where you can choose from a quite broad range of Debian versions. The error listed above is caused by ASAN which is 100% fancy non-functional security testing stuff which I don't think should be even included in production builds.

**Comment by kravietz** [comment]
@sever-sever @nvitaly Working Debian build controls are now maintained here https://github.com/kravietz/pam_tacplus-debian and the package has been submitted for reintroduction into Debian here https://mentors.debian.net/package/libpam-tacplus/

**Comment by sever-sever** [comment]
> @sever-sever @nvitaly Working Debian 11 build controls are now maintained here https://github.com/kravietz/pam_tacplus-debian

wow thanks! Will check
