### ISSUE TITLE
No configure in official tarball

### ISSUE THREAD

**Issue by ffontaine** [kravietz/pam_tacplus#188]
Official tarball (e.g. https://github.com/kravietz/pam_tacplus/releases/download/v1.6.2.1/v1.6.2.1.tar.gz) doesn't ship a configure script. Would it be possible to add one to avoid running autoreconf (which fails if gnulib is not installed).

It would ease the bump of pam_tacplus in buildroot

**Comment by kravietz** [comment]
@ffontaine `configure` depends on `gnulib` run as a first step, so that would be highly dependent on the build system.

**Comment by ffontaine** [comment]
I'm not an expert with gnulib integration but most of the GNU opensource projects that use gnulib are able to provide a configure script in their release tarballs:
- poke: http://ftpmirror.gnu.org/poke/poke-2.4.tar.gz
- coreutils: http://ftpmirror.gnu.org/coreutils/coreutils-9.1.tar.xz

I assume that they're using their own local copy of gnulib to have reproducible builds.

**Comment by kravietz** [comment]
@ffontaine Thanks for the examples, I'll see how they make it. I think I've tried including only requires `gnulib` files already but that led to a terrible mess and I've ended up adding them at build time, but maybe it's done some other way.

**Comment by kravietz** [comment]
@ffontaine Check the https://github.com/kravietz/pam_tacplus/tree/with_configure branch but I still can't get it to work as some files seem to be broken even though they're created by `configure` 🤔

**Comment by kravietz** [comment]
@ffontaine OK, I got it working - simply running `make dist` produces an archive containing working `./configure` and `gnulib` files. Check the newly added files in https://github.com/kravietz/pam_tacplus/releases/tag/v1.7.0 and I will make sure they're being added to the future releases as well.

**Comment by ffontaine** [comment]
Thanks a lot, this is working fine until the installation of `tacc.1` where I got the following build failure:

```
 /usr/bin/install -c -m 644 tacc.1 tacc.1 '/home/fabrice/buildroot/output/per-package/libpam-tacplus/host/nios2-buildroot-linux-gnu/sysroot/usr/share/man/man1'
/usr/bin/install: will not overwrite just-created '/home/fabrice/buildroot/output/per-package/libpam-tacplus/host/nios2-buildroot-linux-gnu/sysroot/usr/share/man/man1/tacc.1' with 'tacc.1'
```

Dropping `dist_man_MANS` or `man1_MANS` from `Makefile.am` will fix the build failure. I can send a PR or I can let you handle it.

**Comment by kravietz** [comment]
@ffontaine No problem, fixed that in HEAD. I will be making a new release in a few days so all these minor changes will go into the release package too.

**Comment by ffontaine** [comment]
Great, I'll wait this release to make the bump on buildroot side.
