### ISSUE TITLE
pam_tacplus license

### ISSUE THREAD

**Issue by overcrook** [kravietz/pam_tacplus#196]
Hello,

if I understand correctly, libtac is licensed under LGPLv3, so it can be dynamically linked to another applications without infecting them with GPL restrictions.

But pam_tacplus is licensed under GPLv3, which means that any PAM-aware application that uses pam_tacplus must also be licensed under a GPL-compatible license. This requirement arises because a PAM-aware application will implicitly load any PAM-module specified in the PAM configuration into its address space.

PAM itself ships under both a permissive license (modified BSD) and the GPL.

My question is: is this on purpose or can you also allow dual licensing for pam_tacplus as well?

**Comment by kravietz** [comment]
@overcrook Probably just an overlook. No problem to distribute `pam_tacplus` under LGPv3 as well, will update license files soon.
