### ISSUE TITLE
Autotools issue on CentOS 6.5

### ISSUE THREAD

**Issue by benschumacher** [kravietz/pam_tacplus#22]
I've seriously tried to figure this out and am having no luck. I've got an autotools issue against HEAD on CentOS 6.5.

Here's what I see when I run configure:

```
$ ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc

... snip ...

checking whether time.h and sys/time.h may both be included... yes
./configure: line 12103: syntax error near unexpected token `AX_CHECK_COMPILE_FLAG'
./configure: line 12103: `AX_CHECK_COMPILE_FLAG("-fstack-protector-all", AX_APPEND_FLAG(["-fstack-protector-all"],[CFLAGS]), )'
```

I've tried a variety of things to get past this -- mostly just moving around the m4 files and such, but nothing seems to work. Would really appreciate if anybody with more autotools-fu could help figure this out. AFAICT this is related to commit 33e9072e542578f30fd67e0be9bce56062f77e58. I'm going to go back to its parent just to make sure.

Thanks.

**Comment by TaJean** [comment]
Hi, 

i have the same problem with CentOS 6.6

i download pam_tacplus-1.3.9.tar, then tar xzvf pam_tacplus-1.3.9.tar
in the folder pam_tacplus-1.3.9 i execute ./auto.sh
and execute ./configure
and receive error : 
checking for size_t... yes
checking whether time.h and sys/time.h may both be included... yes
./configure: line 12103: syntax error near unexpected token `AX_CHECK_COMPILE_FLAG'
./configure: line 12103: `AX_CHECK_COMPILE_FLAG("-fstack-protector-all", AX_APPEND_FLAG(["-fstack-protector-all"],[CFLAGS]), )'
[root@xxxxxxxxxxx pam_tacplus-1.3.9]#

i tried with autoconf 2.63 and autoconf 2.69 but not work, i have the same error.
Can you help me please ?
Thanks a lot
TaJean

**Comment by GeorgeOikonomou** [comment]
Hello

Same problem with RHEL 6.4 and RHEL 6.6:

./configure: line 12103: syntax error near unexpected token `AX_CHECK_COMPILE_FLAG'
./configure: line 12103: `AX_CHECK_COMPILE_FLAG("-fstack-protector-all", AX_APPEND_FLAG(["-fstack-protector-all"],[CFLAGS]), )'

So I would like to ask if someone found a workaround for Centos/RHEL distributions?

 
Thanks
George

**Comment by cyanb** [comment]
Pawel,

Would it be possible to generate a patch for the 1.3.9 release?
I'm running into the same issue on an RHEL67 machine, and 1.4.1 isn't compiling cleanly at all under any OS that I've tried (Sol10x86, RHEL67), with an apparent md5 problem.
