### ISSUE TITLE
trouble with make on native ARM device

### ISSUE THREAD

**Issue by wtinetworkgear** [kravietz/pam_tacplus#42]
Hello,
We are building the pam_tacplus package on a native ARM device.
Of course we follow the steps
autoreconf -i
./configure
make

at the end of the make we are getting errors from the linker
cannot find -lssp_nonshared
cannot find -lssp

Is there a way to disable the stack smashing libs (i am guessing the ssp library is the stack smashing libs) from being called?

Thanks

**Comment by kravietz** [comment]
It doesn't seem to be set on Ubuntu amd64 to apparently something ARM specific. Can you check in the configure.log what could be possibly triggering the -lssp flag - I guess this might be one of the gcc hardening flags.

**Comment by kravietz** [comment]
Compiles OK on Pinebook Pro and even on RiscV (Nezha)
