### ISSUE TITLE
Issue with the supplied md5.h on Sol10 x86 + gcc 4.9.2

### ISSUE THREAD

**Issue by cyanb** [kravietz/pam_tacplus#58]
Compilation is blowing up spectacularly, on a Solaris 10 x86 box w/CSW tooling installed.

I wouldn't even begin to know where to go with this:

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fstack-protector-all -Wl,-z,relro -Wl,-z,now -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -I ./libtac/include -g -O2 -MT libtac/lib/libtac_la-authen_s.lo -MD -MP -MF libtac/lib/.deps/libtac_la-authen_s.Tpo -c libtac/lib/authen_s.c  -fPIC -DPIC -o libtac/lib/.libs/libtac_la-authen_s.o
In file included from libtac/lib/authen_s.c:35:0:
libtac/lib/md5.h:37:17: error: expected declaration specifiers or '...' before '(' token
 void MD5Init__P((MD5_CTX_));
                 ^
libtac/lib/md5.h:38:19: error: expected declaration specifiers or '...' before '(' token
 void MD5Update__P((MD5_CTX_, unsigned char_, UINT4));
                   ^
libtac/lib/md5.h:39:18: error: expected declaration specifiers or '...' before '(' token
 void MD5Final__P((unsigned char[], MD5_CTX_));
                  ^
libtac/lib/authen_s.c: In function 'tac_authen_send':
libtac/lib/authen_s.c:152:2: warning: incompatible implicit declaration of built-in function 'bcopy'
  bcopy(&tb, pkt + pkt_len, sizeof(tb)); /\* packet body beginning _/
  ^
*_\* Error code 1
make: Fatal error: Command failed for target `libtac/lib/libtac_la-authen_s.lo'
Current working directory /export/home/gmelanso/pam_tacplus-master
*** Error code 1
make: Fatal error: Command failed for target`all'

.. thoughts?

**Comment by cyberrbob** [comment]
I had the same error and fixed it by adding space between a function name and a macro __P(...),
pls. look this for info https://lists.freebsd.org/pipermail/freebsd-questions/2006-June/124165.html
so, I had 
MD5Update__P((MD5_CTX, unsigned char, UINT4)) 
and I got 
MD5Update __P((MD5_CTX, unsigned char, UINT4))
not it compiles nice.
