### ISSUE TITLE
About the session_id

### ISSUE THREAD

**Issue by wangyonghe** [kravietz/pam_tacplus#86]
The session_id of the authentication and authorization is inconsistent, the tacplus server cannot identify a session that belongs to a session of SSH. 
BTW,  the accounting request cannot be send out when executing command in shell

**Comment by pprindeville** [comment]
Can you give a little more detail?  Inconsistent how?  Do you have debugging logs or packet traces?

And what version are you running?

The reorganization that's in the works will keep the session_id in the session object, and this will fix a couple of issues.

See https://github.com/jeroennijhof/pam_tacplus/pull/78/files#diff-918c12badfa2544a1435316a40d2cdf3R85 in particular libtac/authen_s.c line 154 for example.
